name: ResourcePackManager
main: com.magmaguy.resourcepackmanager.ResourcePackManager
version: 1.2.1
api-version: 1.14
author: MagmaGuy
softdepend:
- EliteMobs
- FreeMinecraftModels
- ModelEngine
- Nova
- Oraxen
- ItemsAdder
- BackpackPlus
- vane-core
- RealisticSurvival

commands:
  resourcepackmanager:
    aliases:
      - rspm
    description: "Main command"