name: Maven Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ResourcePackManager
        path: target/ResourcePackManager.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: ResourcePackManager
        
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ResourcePackManager.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
